jetcache:
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri: redis://123456@192.168.2.70:7371/0
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 10000
      stat-view-servlet:
        allow: ''
        enabled: true
        login-password: nstc
        login-username: nstc
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        profile-enable: true
        session-stat-enable: true
        url-pattern: /*
    dynamic:
      datasource:
        bems:
          connectionTimeout: 30000
          driver-class-name: oracle.jdbc.OracleDriver
          idleTimeout: 60000
          jdbc-url: ${spring.datasource.dynamic.datasource.workflow.url}
          leakDetectionThreshold: 5000
          maxLifetime: 60000
          maxPoolSize: 50
          minIdle: 10
          password: 11111111
          poolName: bems
          url: jdbc:oracle:thin:@192.168.2.109:1521:NSDEV
          username: bems
          schema: classpath*:db/workflow/schema.sql
        test:
          driver-class-name: oracle.jdbc.OracleDriver
          password: 11111111
          url: jdbc:oracle:thin:@192.168.2.109:1521:NSDEV
          username: ebs
        ebs:
          connectionTimeout: 30000
          driver-class-name: oracle.jdbc.OracleDriver
          idleTimeout: 60000
          leakDetectionThreshold: 5000
          maxLifetime: 60000
          maxPoolSize: 100
          minIdle: 10
          password: 11111111
          poolName: ebs
          url: jdbc:oracle:thin:@192.168.2.109:1521:NSDEV
          username: ebs
        workflow:
          connectionTimeout: 30000
          driver-class-name: oracle.jdbc.OracleDriver
          idleTimeout: 60000
          jdbc-url: ${spring.datasource.dynamic.datasource.workflow.url}
          leakDetectionThreshold: 5000
          maxLifetime: 60000
          maxPoolSize: 50
          minIdle: 10
          password: 11111111
          poolName: workflow
          url: jdbc:oracle:thin:@192.168.2.109:1521:NSDEV
          username: bems
      druid:
        wall:
          commentAllow: true
          multiStatementAllow: true
          noneBaseStatementAllow: true
          variantCheck: false
      enabled: true
      p6spy: false
      primary: ebs
      seata: false
      strict: true
  flyway:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
  redis:
    host: 192.168.2.70
    port: 7371
    database: 0
    password: 123456
    timeout: 10000
    lettuce:
      pool:
        max-wait: 10000
feign:
  client:
    config:
      default:
        connect-timeout: 300000
        read-timeout: 600000
  okhttp:
    enabled: true
  hystrix:
    enabled: true
# 设置熔断时间为
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 # 设置hystrix的超时时间为30s