server:
  port: 80
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.2.109:1521/NSDEV
    username: lianxi_sk
    password: "11111111"
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: true
    baseline-on-migrate: true
  cloud:
    compatibility-verifier:
      enabled: false
nsosp:
  job:
    accessToken: ''
    admin:
      addresses: http://192.168.2.70:7090/nsosp-job-admin
    executor:
      address: ''
      appname: wuyc-job
      ip: ''
      logpath: /home/user/project/nsosp-job-logs/jobhandler
      logretentiondays: 30
      port: 6166
nstc:
  name: "nine star technology company"
  dept:
    - name: "sk"
      addr: "bj"
      persions: 7
    - name: "vue"
      addr: "bj"
      persions: 11
  persion:
    name: "tony"
    age: 22
    sex: "man"