nstc:
    dssc:
        need-sgin: false
        supplier: NetServer
        net:
            test-sing-prefix: DFCWTEST
            CommunicateMode: 1
            MaxConnections: 5
            MinZipSize: 200
            ServerIP: 211.161.120.22
            ServerPort: 50001
            Timeout: 30000
            UsedConnectionPool: false
            ZipMode: false
            connectionmode: 1
            encoding: GBK
            gc: 0
            orderdn: 0
            servicetestinterval: 10000
            servicetestistest: 'yes'
            snmode: 1
    jetcache:
        host: 192.168.2.70
        password: NSTCG20&123456
        port: 7371
    uas:
        token-validity-seconds: 720000
        signing-key: uas123
        limitOneUserLogin: false
    user:
        sys-type: N9FSS
        qryUnitPermission: true
        initRes:
            filePath: D:/initRes
    feign:
        mdm-service: http://192.168.2.70:5021/mdm
    datasource:
        names: bems,workflow
        primary-key: bems

    mdm:
        client:
            serviceId: "bems-service"
            servicePrefix: /bems
    service:
        aims:
            context-path: /ebs
            hosted-service: ebs-service
    flyway:
        dialect: oracle
        scope: table,data
        table: BEMS_VERSION
        outOfOrder: true
        allowRepair: true
spring:
    test: true
    activiti:
        check-process-definitions: false
        database-schema-update: false
        db-history-used: true
        history-level: full
        job-executor-activate: true
    cloud:
        stream:
            bindings:
                user_biz_input:
                    content-type: application/json
                    destination: user_biz_input
                    group: user-client
                user_data_info_input:
                    content-type: application/json
                    destination: user_data_info_input
                    group: user-client
    freemarker:
        charset: UTF-8
        request-context-attribute: request
        settings:
            number_format: 0.##########
        suffix: .ftl
        templateLoaderPath: classpath:/templates/
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: always
    main:
        allow-bean-definition-overriding: true
    rabbitmq:
        host: 192.168.2.70
        password: G20MQ
        port: 7672
        username: G20MQ

swagger:
    enabled: true
    pathMapping: /

nsosp:
    job:
        accessToken: ''
        admin:
            addresses: http://192.168.2.70:7090/nsosp-job-admin
        executor:
            address: ''
            appname: bems-job
            ip: ''
            logpath: /home/user/project/nsosp-job-logs/jobhandler
            logretentiondays: 30
            port: 7904

feign:
    client:
        config:
            default:
                connect-timeout: 300000
                read-timeout: 600000
    okhttp:
        enabled: true

logging:
    level:
        root: info
        
# chengdu portal
file:
    uploadDir: /home/user/uploads
user:
    systemopno:
        system1: user-web0001,user-web00011,user-webQuery00011,user-webOpt,user-webUpdate,user-webRalationRole,user-webRest,user-webRalationRoleBatch,user-webRestBatch,user-web00013,user-web00014,user-web00016,user-web00017,user-web00018,user-web00019,user-web00012,user-webQuery00012,user-webRoleOpt,user-webRoleUpdate,user-web000121,user-web000122,user-web000123,user-web000124,user-web00001,user-web00002,user-web00003,user-web00004,user-web00005,user-web00006,user-web00007,user-web00008,user-web00009,user-web00010,user-web00011,user-web00012,user-web00013,mdmk01,mdm011,mdm012,mdm013,mdm014,mdm015,mdm016,mdm017,mdm018,user-f172149fa845e941,user-7b1a372de4e4889a,user-e2dcc4a2b74fce5c,user-e23b5f5b9b3dedee,user-7a3c48d5da63811f,user-8750d9b293aaf419,user-d7f185f3ad665705,user-3d4416e78760a77a,user-d65f39e90fde5252,user-f906b4b5cae7b035,user-617622e679f7cd37,user-69c3900146a2170f
        audit1: user-web0001,user-web00011,user-webQuery00011,user-web00012,user-webQuery00012
        #system1: user-web0001,user-web00002,user-web00003,user-web00004,user-web00005,user-web00006,user-web00007,user-web00008,user-web00009,user-web00010,user-web00011,user-webQuery00011,user-webOpt,user-webUpdate,user-webRalationRole,user-webRest,user-webRalationRoleBatch,user-webRestBatch,user-web00013,user-web00014,user-web00016,user-web00017,user-web00018,user-web00019,user-web00012,user-webQuery00012,user-webRoleOpt,user-webRoleUpdate,user-web000121,user-web000122,user-web000123,user-web000124,mdm01,mdm011,mdm012,mdm014,mdm015
        #audit1: user-web0001,user-web00011,user-webQuery00011,user-web00012,user-webQuery00012
mdm:
  swagger-open: true
  full-sync-cron-expression: "* */5 *  * * ?"
  diff-sync-cron-expression: "* */1 *  * * ?"
  sync-failed-retry-times: 3
app:
 center:
    database:
      type: 19c
statistics:
    from: n9

## redis
    redis:
        host: 192.168.2.70
        password: 123456
        port: 7371
        lettuce:
            pool:
                min-idle: 5
                max-idle: 50
                max-active: 100
                max-wait: 100
jetcache:
    areaInCacheName: false
    local:
        default:
            type: caffeine
            keyConvertor: fastjson
    remote:
        default:
            type: redis.lettuce
            keyConvertor: fastjson
            uri: redis://123456@192.168.2.70:7371/0