-- 2021060218_dengzq_银行账户登记使用基础数据表
-- 新增 银行账户登记 开户行（总行）数据视图 DSY_V_ELE_KHHZH
CREATE
  OR REPLACE VIEW DSY_V_ELE_KHHZH AS
 SELECT
  "ADMDIV",
  "GUID",
  "NAME",
  "ISLEAF",
  "DESGUID",
  "LEVELNO",
  "SRCSCALE",
  "REMARK",
  "STARTTIME",
  "CREATETIME",
  "PINYIN",
  "ALIAS",
  "VERSION",
  "SUPERGUID",
  "ENDTIME",
  "SRCGUID",
  "CODE",
  "DBVERSION",
  "STATUS",
  "YEAR",
  "PROVINCE"
FROM
  P#FASP_T_PUBDEBT_ZQR
WHERE
  GUID LIKE '0102%'
  OR GUID LIKE '0103%'
  OR GUID LIKE '0104%'
  OR GUID LIKE '0105%'
  OR GUID LIKE '0106%'
  OR GUID LIKE '0107%'
ORDER BY
	GUID ASC;
