# 应用配置 spring profile配置
ACTIVE_PROFILE:

# 数据库配置
# 数据库类型
DB_TYPE: oracle
# 主数据源
PRIMARY_DB: ebs
# bems数据源配置
BEMS_DB_CLASS_NAME: oracle.jdbc.OracleDriver
BEMS_DB_URL: jdbc:oracle:thin:@192.168.2.109:1521:NSDEV
BEMS_DB_POLLNAME: bems
BEMS_DB_USERNAME: bems
BEMS_DB_PASSWORD: 11111111
# ebs数据源配置
EBS_DB_CLASS_NAME: oracle.jdbc.OracleDriver
EBS_DB_URL: jdbc:oracle:thin:@192.168.2.109:1521:NSDEV
EBS_DB_POLLNAME: ebs
EBS_DB_USERNAME: ebs
EBS_DB_PASSWORD: 11111111
# 工作流数据源配置(大部分时候与bems同库)
ACT_DB_CLASS_NAME: ${BEMS_DB_CLASS_NAME}
ACT_DB_URL: ${BEMS_DB_URL}
ACT_DB_POLLNAME: workflow
ACT_DB_USERNAME: ${BEMS_DB_USERNAME}
ACT_DB_PASSWORD: ${BEMS_DB_PASSWORD}

# redis配置
REDIS_HOST: 192.168.2.70
REDIS_PORT: 7371
REDIS_PASSWORD: 123456
REDIS_DATABASE: 1

#amq配置
RABBITMQ_HOST: 192.168.2.70
RABBITMQ_PORT: 7672
RABBITMQ_USERNAME: G20MQ
RABBITMQ_PASSWORD: G20MQ

# JETCACHE配置
JETCACHE_REDIS_URL: redis://123456@192.168.2.70:7371/0

# BP服务地址
BP_SERVICE_ADDRESS: http://192.168.20.194:9281/bp-server

# 自动任务服务
NSOSP_SERVICE_ADDRESS: http://192.168.2.70:7090/nsosp-job-admin

# 服务注册信息 目前大部分使用用于feign调用
# 大部分时候, 很多业务模块是集中到ebs中部署的, 因此默认配置直接获取的是ebs服务名, 如果单独部署某个模块, 则需要修改对应服务注册信息
# BEMS
GCM_BEMS_HOSTED_SERVICE: bems-service
GCM_BEMS_CONTEXT_PATH: /bems
# EBS
GCM_EBS_HOSTED_SERVICE: ebs-service
GCM_EBS_CONTEXT_PATH: /ebs
# 账户
GCM_AIMS_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_AIMS_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
# 预算
GCM_CFB_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_CFB_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
# 收款
GCM_CTMS_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_CTMS_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
# 融资
GCM_GDT_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_GDT_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
# 付款
GCM_PTMS_HOSTED_SERVICE: nstc-ptms-service
GCM_PTMS_CONTEXT_PATH: /
# 资金集中
GCM_FTS_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_FTS_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
# 资金计划
GCM_RPLS_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_RPLS_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
#库存现金台账
GCM_CAM_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_CAM_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
#现金流台账
GCM_CFAS_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_CFAS_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
#集团票据
GCM_GDPS_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_GDPS_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
#担保
GCM_GWMS_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_GWMS_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
#授信
GCM_CLMS_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_CLMS_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
#财资结算
GCM_TSS_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_TSS_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}
#借款
GCM_LMS_HOSTED_SERVICE: ${GCM_EBS_HOSTED_SERVICE}
GCM_LMS_CONTEXT_PATH: ${GCM_EBS_CONTEXT_PATH}