spring:
  autoconfigure:
    #使用动态数据源时，排除原生Druid的快速配置类
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      filter:
        stat:
          enabled: true
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 10000
      stat-view-servlet:
        allow: ''
        enabled: true
        login-password: nstc
        login-username: nstc
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        profile-enable: true
        session-stat-enable: true
        url-pattern: /*
    dynamic:
      enabled: true
      # 连接池配置：
      # 1、每个数据源可通过type属性单独设置连接池。若无特殊需要并不建议
      # 2、type 不是必填字段 ，在没有设置type的时候系统会自动按以下顺序查找并使用连接池
      #    Druid > HikariCp > BeeCp > DBCP2 > Spring Basic
      # 3、以下为使用Druid时的全局参数，每个数据源会继承此配置。每个数据源也可单独配置来覆盖全局配置
      druid:
        # 参考 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE-wallfilter
        wall:
          # 允许语句中存在注释，Oracle的用户不用担心，Wall能够识别hints和注释的区别
          commentAllow: true
          # 允许一次执行多条语句
          multiStatementAllow: true
          # 允许非基本语句的其他语句(DDL)
          noneBaseStatementAllow: true
          # 不检测使用“禁用的变量”
          variantCheck: false
      datasource:
        bems:
          driver-class-name: ${BEMS_DB_CLASS_NAME}
          url: ${BEMS_DB_URL}
          poolName: ${BEMS_DB_POLLNAME}
          username: ${BEMS_DB_USERNAME}
          password: ${BEMS_DB_PASSWORD}
          schema: classpath*:db/workflow/schema.sql
        ebs:
          driver-class-name: ${EBS_DB_CLASS_NAME}
          url: ${EBS_DB_URL}
          poolName: ${EBS_DB_POLLNAME}
          username: ${EBS_DB_USERNAME}
          password: ${EBS_DB_PASSWORD}
        workflow:
          driver-class-name: ${ACT_DB_CLASS_NAME}
          poolName: ${ACT_DB_POLLNAME}
          url: ${ACT_DB_URL}
          username: ${ACT_DB_USERNAME}
          password: ${ACT_DB_PASSWORD}
      # 设置默认的数据源
      primary: ${PRIMARY_DB}
      # 默认false，建议线上关闭。也可单独在每个数据源设置此参数
      p6spy: false
      # 关闭seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
      seata: false
      # 设置严格模式，默认false。启用时，未匹配到指定数据源时候会抛出异常；不启用时，则使用默认数据源.
      strict: true
  # 配置redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DATABASE}
# 配置redis缓存
jetcache:
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri: ${JETCACHE_REDIS_URL}