package com.cnpc.sais.ibp.auth.pojo;

import java.util.List;
import java.util.Set;

import com.cnpc.sais.ibp.auth.util.AuthConstant;

/**
 * PAuthMenu generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("serial")
public class PAuthMenu implements java.io.Serializable {

	// Fields

	private String menuId;

	private String menuEName;

	private String menuCName;

	private String menuOName;

	private String menuUrl;

	private String isLeaf;

	private String menuHint;

	private String orderNum;

	private String parentMenuId;

	private String visible;

	private String imgUrl;

	private Set<PAuthMenuFunc> menuFuncs;

	// 下一级子菜单，不递归
	private List<PAuthMenu> childrenMenus;

	@SuppressWarnings("unused")
	private String excludeProperties = ",menuFuncs,childrenMenus,leafMenu,";

	// Constructors

	/** default constructor */
	public PAuthMenu() {
	}

	/** full constructor */
	public PAuthMenu(String menuEName, String menuCName, String menuUrl,
			String isLeaf, String menuHint, String orderNum, String imgUrl) {
		this.menuEName = menuEName;
		this.menuCName = menuCName;
		this.menuUrl = menuUrl;
		this.isLeaf = isLeaf;
		this.menuHint = menuHint;
		this.orderNum = orderNum;
		this.imgUrl = imgUrl;
	}

	// Property accessors

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public String getMenuEName() {
		return this.menuEName;
	}

	public void setMenuEName(String menuEName) {
		this.menuEName = menuEName;
	}

	public String getMenuCName() {
		return this.menuCName;
	}

	public void setMenuCName(String menuCName) {
		this.menuCName = menuCName;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	public String getIsLeaf() {
		return this.isLeaf;
	}

	public void setIsLeaf(String isLeaf) {
		this.isLeaf = isLeaf;
	}

	public String getMenuHint() {
		return this.menuHint;
	}

	public void setMenuHint(String menuHint) {
		this.menuHint = menuHint;
	}

	public String getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	public String getParentMenuId() {
		return parentMenuId;
	}

	public void setParentMenuId(String parentMenuId) {
		this.parentMenuId = parentMenuId;
	}

	public List<PAuthMenu> getChildrenMenus() {
		return childrenMenus;
	}

	public void setChildrenMenus(List<PAuthMenu> childrenMenus) {
		this.childrenMenus = childrenMenus;
	}

	public Set<PAuthMenuFunc> getMenuFuncs() {
		return menuFuncs;
	}

	public void setMenuFuncs(Set<PAuthMenuFunc> menuFuncs) {
		this.menuFuncs = menuFuncs;
	}

	public String getImgUrl() {
		return imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	/**
	 * 是否为叶子菜单
	 * 
	 * @return
	 */
	public boolean isLeafMenu() {
		return AuthConstant.LEAF_MENU_FLAG.equals(getIsLeaf());
	}

	public boolean equals(Object menu) {
		if (menu instanceof PAuthMenu) {
			PAuthMenu menu1 = (PAuthMenu) menu;
			return this.getMenuId().equals(menu1.getMenuId());
		}
		return false;
	}

	public String getVisible() {
		return visible;
	}

	public void setVisible(String visible) {
		this.visible = visible;
	}

	public String getMenuOName() {
		return menuOName;
	}

	public void setMenuOName(String menuOName) {
		this.menuOName = menuOName;
	}

}