-- 总限额分解工作流及授权脚本
DELETE FROM DSY_T_WF_NODE WHERE WF_ID = '100255';
insert into DSY_T_WF_NODE (NODE_ID, NODE_CODE, NODE_NAME, NODE_TYPE, WF_ID, WF_NAME, AD_CODE, SET_YEAR, NODE_NEXT_CODE, CONDITION_ID)
values (1002551, '1', '录入', 'BEGIN', 100255, '债券总限额分解流程', null, 2020, '2', '#');
insert into DSY_T_WF_NODE (NODE_ID, NODE_CODE, NODE_NAME, NODE_TYPE, WF_ID, WF_NAME, AD_CODE, SET_YEAR, NODE_NEXT_CODE, CONDITION_ID)
values (1002552, '2', '审核', 'END', 100255, '债券总限额分解流程', null, 2020, null, '#');
DELETE FROM DSY_T_WF_NODE_ROLE WHERE WF_ID = '100255';
insert into DSY_T_WF_NODE_ROLE (NODE_ID, ROLE_ID, WF_ID, AD_CODE, SET_YEAR)
values (1002551, 'debt_sheng_003', 100255, null, null);
insert into DSY_T_WF_NODE_ROLE (NODE_ID, ROLE_ID, WF_ID, AD_CODE, SET_YEAR)
values (1002552, 'debt_sheng_003', 100255, null, null);
-- 需求批次视图
create or replace view dsy_v_ele_fxpc as
 select "ADMDIV","GUID","NAME","ISLEAF","DESGUID","LEVELNO","SRCSCALE","REMARK","STARTTIME","CREATETIME","PINYIN","ALIAS","VERSION","SUPERGUID","ENDTIME","SRCGUID","CODE","DBVERSION","STATUS","YEAR","PROVINCE","EXTEND1","EXTEND2","EXTEND3","EXTEND4","EXTEND5"
 from  P#FASP_T_PUBDEBT_FXPC;
